/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.doit.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.*;

/**
 * Ставка
 *
 * @author slavb
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
public class Bid implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private BigDecimal price;

    @ManyToOne(targetEntity = Work.class)
    private Work work;

    @ManyToOne(targetEntity = BussinessEntity.class)
    private BussinessEntity bussinessEntity;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Work getWork() {
        return this.work;
    }

    public void setWork(Work work) {
        this.work = work;
    }

    public BussinessEntity getBussinessEntity() {
        return this.bussinessEntity;
    }

    public void setBussinessEntity(BussinessEntity bussinessEntity) {
        this.bussinessEntity = bussinessEntity;
    }

}
