/**
 * This file was generated by the JPA Modeler
 */ 

package ru.ilb.doit.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * Хозйствующий субъект
 * @author slavb
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
public class BussinessEntity implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @Basic
    private String login;

    @XmlTransient
    @OneToMany(targetEntity = Work.class,mappedBy = "bussinessEntity")
    private List<Work> works;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public List<Work> getWorks() {
        return this.works;
    }

    public void setWorks(List<Work> works) {
        this.works = works;
    }


}
