/**
 * This file was generated by the JPA Modeler
 */ 

package ru.ilb.doit.model;

import java.io.Serializable;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.xml.bind.annotation.*;

/**
 * Филическое лицо
 * @author slavb
 */

@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@DiscriminatorValue("1")
public class PrivatePerson extends BussinessEntity implements Serializable { 



}
